# Generated by Django 4.0.6 on 2022-07-11 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news_app', '0004_journalist_alter_article_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='journalist',
            name='biodeta',
            field=models.TextField(blank=True),
        ),
    ]
